import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
import "./styles/index.css";
import "./styles/aura.css";

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// Registers the service worker generated by vite-plugin-pwa at build time.
// This import is a no-op during `npm run dev` and only takes effect in a
// production build (`npm run build` + serve/deploy), which is what makes
// the app installable as a PWA.
if (import.meta.env.PROD) {
  import("virtual:pwa-register").then(({ registerSW }) => {
    registerSW({ immediate: true });
  });
}
